// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JlizBankEntity.JlizEntity
{
    public partial class BankPersonalInfo
    {
        public BankPersonalInfo()
        {
            BankAccount = new HashSet<BankAccount>();
        }

        public Guid CustomerId { get; set; }
        public string IdentityNum { get; set; }
        public string UserName { get; set; }
        public DateTime Birthday { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public DateTime InitDate { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string Images { get; set; }

        public virtual ICollection<BankAccount> BankAccount { get; set; }
    }
}