// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JlizBankEntity.JlizEntity
{
    public partial class BranchBank
    {
        public BranchBank()
        {
            BankAccount = new HashSet<BankAccount>();
        }

        public string BankId { get; set; }
        public string BankName { get; set; }
        public DateTime InitDate { get; set; }
        public DateTime? ModifyDate { get; set; }

        public virtual ICollection<BankAccount> BankAccount { get; set; }
    }
}